[live]
title = "네이버 공연 live beta"
url = "https://live.naver.com/"
entrySelector = "ul.list-item li.item"
titleSelector = "div.detail-info a"
linkSelector = "div.detail-info a"
contentSelector = "p.date.ico-before"
imageSelector = "div.mask-box img._lazyImage"
waitUntil = "networkidle"

[top]
title = "네이버 공연 live beta ─ 하이라이트"
url = "https://live.naver.com/"
entrySelector = "div.eg-flick-camera div.video-box.eg-flick-panel:nth-child(1),div.eg-flick-camera div.video-box.eg-flick-panel:nth-child(2),div.eg-flick-camera div.video-box.eg-flick-panel:nth-child(3),div.eg-flick-camera div.video-box.eg-flick-panel:nth-child(4)"
titleSelector = "p.sub-title.ellipsis2"
linkSelector = "a.video"
contentSelector = "p.date.ellipsis"
imageSelector = "img._lazyImage"
waitUntil = "networkidle"

[hot]
title = "네이버 공연 live beta ─ HOT"
url = "https://live.naver.com/hot"
entrySelector = "ul.list-item li.item"
titleSelector = "div.detail-info a"
linkSelector = "div.detail-info a"
contentSelector = "p.date.ico-before"
imageSelector = "div.mask-box img._lazyImage"
waitUntil = "networkidle"

[channel]
title = "네이버 공연 live beta ─ 채널"
url = "https://live.naver.com/"
entrySelector = "div.channel-list-box div.channel-list div div div.channel-item"
titleSelector = "div.info-txt p.txt"
linkSelector = "a.lnk-channel"
imageSelector = "div.mask img._lazyImage"
waitUntil = "networkidle"

[store]
title = "네이버 공연 live beta ─ 후원유료"
url = "https://live.naver.com/store"
entrySelector = "ul.list-item li.item"
titleSelector = "a.detail-title"
linkSelector = "a.detail-title"
contentSelector = "p.date.ico-before"
imageSelector = "img._lazyImage"
waitUntil = "networkidle"

[vod]
title = "네이버 공연 live beta ─ 다시보기"
url = "https://live.naver.com/vod"
entrySelector = "ul.list-item li.item"
titleSelector = "a.detail-title"
linkSelector = "a.detail-title"
contentSelector = "p.sub-info span.txt:nth-child(2)"
imageSelector = "img._lazyImage"
waitUntil = "networkidle"

[schedule]
title = "네이버 공연 live beta ─ 전체일정"
url = "https://live.naver.com/schedule"
entrySelector = "ul.list-item.schedule_list li.item.schedule_item"
titleSelector = "a.detail-title"
linkSelector = "a.detail-title"
contentSelector = "p.date.ico-before"
waitUntil = "networkidle"

